# Generated by Django 4.0 on 2023-03-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='work_hour',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
