# Generated by Django 4.1.1 on 2023-03-19 20:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("passenger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarsAvailable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_name", models.CharField(max_length=100, null=True)),
                (
                    "car_image",
                    models.ImageField(default="default.jpg", upload_to="images/cars/"),
                ),
                ("car_seats", models.IntegerField(blank=True, null=True)),
                ("car_luggage_space", models.IntegerField(blank=True, null=True)),
                ("price", models.IntegerField()),
                ("booked", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="bookingdb",
            name="guess_id",
            field=models.CharField(
                blank=True, editable=False, max_length=200, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="bookingdb",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
