# Generated by Django 4.1.1 on 2023-03-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passenger", "0002_carsavailable_bookingdb_guess_id_alter_bookingdb_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingdb",
            name="guess_id",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
