# Generated by Django 4.0 on 2023-03-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0002_bookingdb_airline_bookingdb_flight_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='way_point_1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='way_point_2',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
