# Generated by Django 4.0 on 2023-03-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0002_alter_bookingdb_work_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='work_hour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
