# Generated by Django 4.0 on 2023-03-16 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0003_alter_subcriber_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcriber',
            new_name='Subscriber',
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={},
        ),
    ]
