# Generated by Django 4.0 on 2023-03-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0003_alter_bookingdb_work_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='dropoff_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdb',
            name='dropoff_airport',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdb',
            name='flight_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookingdb',
            name='pick_up_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdb',
            name='pickup_airport',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
