# Generated by Django 4.1.1 on 2023-03-20 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passenger", "0004_rename_guess_id_bookingdb_booking_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingdb",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 3, 20, 2, 2, 3, 938384, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
