# Generated by Django 4.1.1 on 2023-03-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passenger", "0006_alter_bookingdb_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingDb_part2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pick_up_address",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "dropoff_address",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "dropoff_airport",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "pickup_airport",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("distance", models.CharField(max_length=150, null=True)),
                ("way_point_1", models.CharField(blank=True, max_length=250)),
                ("way_point_2", models.CharField(blank=True, max_length=250)),
                ("airline", models.CharField(max_length=200)),
                ("work_hour", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "flight_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "booking_part2",
                "verbose_name_plural": "booking_part2",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="BookngDb_final",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("phone_number", models.IntegerField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "booking_final",
                "verbose_name_plural": "booking_final",
                "ordering": ["-date"],
            },
        ),
        migrations.AlterModelOptions(
            name="bookingdb",
            options={
                "ordering": ["-date"],
                "verbose_name": "booking_part1",
                "verbose_name_plural": "booking_part1",
            },
        ),
        migrations.RemoveField(
            model_name="bookingdb",
            name="airline",
        ),
        migrations.RemoveField(
            model_name="bookingdb",
            name="distance",
        ),
        migrations.RemoveField(
            model_name="bookingdb",
            name="dropoff_address",
        ),
        migrations.RemoveField(
            model_name="bookingdb",
            name="dropoff_airport",
        ),
        migrations.RemoveField(
            model_name="bookingdb",
            name="email",
        ),
        migrations.RemoveField(
            model_name="bookingdb",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="bookingdb",
            name="flight_number",
        ),
        migrations.RemoveField(
            model_name="bookingdb",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="bookingdb",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="bookingdb",
            name="pick_up_address",
        ),
        migrations.RemoveField(
            model_name="bookingdb",
            name="pickup_airport",
        ),
        migrations.RemoveField(
            model_name="bookingdb",
            name="way_point_1",
        ),
        migrations.RemoveField(
            model_name="bookingdb",
            name="way_point_2",
        ),
        migrations.RemoveField(
            model_name="bookingdb",
            name="work_hour",
        ),
    ]
