# Generated by Django 4.1.1 on 2023-03-20 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passenger", "0007_bookingdb_part2_bookngdb_final_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingdb_part2",
            name="booking_id",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 3, 20, 10, 21, 32, 967134, tzinfo=datetime.timezone.utc
                ),
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookngdb_final",
            name="booking_id",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 3, 20, 10, 21, 45, 103265, tzinfo=datetime.timezone.utc
                ),
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookingdb",
            name="booking_id",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 3, 20, 10, 22, 13, 9553, tzinfo=datetime.timezone.utc
                ),
                max_length=200,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
