# Generated by Django 4.1.1 on 2023-03-20 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "passenger",
            "0008_bookingdb_part2_booking_id_bookngdb_final_booking_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingdb_part2",
            name="way_point_1",
        ),
        migrations.RemoveField(
            model_name="bookingdb_part2",
            name="way_point_2",
        ),
        migrations.AlterField(
            model_name="bookngdb_final",
            name="phone_number",
            field=models.IntegerField(
                default=0000000000
            ),
            preserve_default=False,
        ),
    ]
