# Generated by Django 4.1.1 on 2023-03-21 09:41

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("passenger", "0009_remove_bookingdb_part2_way_point_1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Active_Bookings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("phone_number", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("service_details", models.CharField(max_length=50)),
                ("pick_up_date", models.DateField()),
                ("pick_up_time_hour", models.CharField(max_length=100)),
                ("pick_up_time_mins", models.CharField(max_length=100)),
                ("number_of_passenger", models.IntegerField()),
                ("number_of_luggages", models.IntegerField()),
                (
                    "pick_up_address",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "dropoff_address",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "dropoff_airport",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "pickup_airport",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("distance", models.CharField(max_length=150, null=True)),
                ("airline", models.CharField(max_length=200)),
                ("work_hour", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "flight_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("car_name", models.CharField(max_length=100, null=True)),
                ("car_model", models.CharField(max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("booking_id", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Active Booking",
                "verbose_name_plural": "Active Booking",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Carselection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_id", models.CharField(max_length=100)),
                ("booking_id", models.CharField(max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Booking Cars",
                "verbose_name_plural": "Booking Cars",
                "ordering": ["-date"],
            },
        ),
        migrations.AlterModelOptions(
            name="carsavailable",
            options={
                "verbose_name": "Cars Available",
                "verbose_name_plural": "Cars Available",
            },
        ),
        migrations.AddField(
            model_name="carsavailable",
            name="boking_per_hour",
            field=models.IntegerField(
                default=00
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carsavailable",
            name="booking_id",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 3, 21, 9, 40, 14, 58895, tzinfo=datetime.timezone.utc
                ),
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carsavailable",
            name="car_model",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 3, 21, 9, 41, 8, 143951, tzinfo=datetime.timezone.utc
                ),
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="carsavailable",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
