# Generated by Django 4.1.1 on 2023-03-21 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("passenger", "0010_active_bookings_carselection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carsavailable",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
