# Generated by Django 4.1.1 on 2023-03-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("passenger", "0011_alter_carsavailable_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carsavailable",
            name="booking_id",
        ),
    ]
