# Generated by Django 4.1.1 on 2023-03-21 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passenger", "0012_remove_carsavailable_booking_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="active_bookings",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="carsavailable",
            name="car_luggage_space",
            field=models.IntegerField(
                default=7
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="carsavailable",
            name="car_name",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 3, 21, 10, 49, 1, 853695, tzinfo=datetime.timezone.utc
                ),
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="carsavailable",
            name="car_seats",
            field=models.IntegerField(
                default=7
            ),
            preserve_default=False,
        ),
    ]
