# Generated by Django 4.1.1 on 2023-03-16 08:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rentals",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("car_model", models.CharField(max_length=50)),
                ("car_rent_img", models.ImageField(upload_to="rents/")),
                ("car_rent_img_1", models.ImageField(null=True, upload_to="rents/")),
                ("car_rent_img_2", models.ImageField(null=True, upload_to="rents/")),
                ("car_rent_img_3", models.ImageField(null=True, upload_to="rents/")),
                ("car_rent_img_4", models.ImageField(null=True, upload_to="rents/")),
                ("car_rent_img_5", models.ImageField(null=True, upload_to="rents/")),
                ("price", models.IntegerField()),
                ("description", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rents",
                "verbose_name_plural": "Rents",
                "ordering": ["-timestamp"],
            },
        ),
    ]
