# Generated by Django 4.1.1 on 2023-03-16 10:48

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentForm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("car_id", models.CharField(max_length=60)),
                ("user_id", models.CharField(max_length=60)),
                ("user_name", models.CharField(max_length=60)),
                ("email_user", models.EmailField(max_length=100)),
                ("hours", models.IntegerField()),
                ("Days", models.IntegerField()),
                ("new_price", models.IntegerField()),
                ("car_rent_name", models.CharField(max_length=50)),
                ("car_rent_model", models.CharField(max_length=50)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("ordered", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Rents Form",
                "verbose_name_plural": "Rents Form",
                "ordering": ["-date"],
            },
        ),
        migrations.AlterField(
            model_name="rentals",
            name="car_rent_img_1",
            field=models.ImageField(upload_to="rents/"),
        ),
        migrations.AlterField(
            model_name="rentals",
            name="car_rent_img_2",
            field=models.ImageField(upload_to="rents/"),
        ),
        migrations.AlterField(
            model_name="rentals",
            name="car_rent_img_3",
            field=models.ImageField(
                default=datetime.datetime(
                    2023, 3, 16, 10, 47, 51, 919706, tzinfo=datetime.timezone.utc
                ),
                upload_to="rents/",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rentals",
            name="car_rent_img_4",
            field=models.ImageField(
                default=datetime.datetime(
                    2023, 3, 16, 10, 48, 19, 780994, tzinfo=datetime.timezone.utc
                ),
                upload_to="rents/",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rentals",
            name="car_rent_img_5",
            field=models.ImageField(
                default=datetime.datetime(
                    2023, 3, 16, 10, 48, 38, 482260, tzinfo=datetime.timezone.utc
                ),
                upload_to="rents/",
            ),
            preserve_default=False,
        ),
    ]
