# Generated by Django 4.1.1 on 2023-03-26 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentform",
            name="billing_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rentform",
            name="order_key",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 3, 26, 0, 57, 35, 609587, tzinfo=datetime.timezone.utc
                ),
                max_length=150,
            ),
            preserve_default=False,
        ),
    ]
