# Generated by Django 4.1.1 on 2023-03-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0002_rentform_alter_rentals_car_rent_img_1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rentform",
            old_name="user_name",
            new_name="user_names",
        ),
    ]
