# Generated by Django 4.1.1 on 2023-03-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0002_rentform_billing_status_rentform_order_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="Active_orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_id", models.CharField(max_length=50)),
                ("billing_status", models.BooleanField(default=False)),
                ("order_key", models.CharField(max_length=150)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Active Orders",
                "verbose_name_plural": "Active Orders",
                "ordering": ["-date"],
            },
        ),
        migrations.RemoveField(
            model_name="rentform",
            name="billing_status",
        ),
        migrations.RemoveField(
            model_name="rentform",
            name="order_key",
        ),
    ]
