# Generated by Django 4.1.1 on 2023-03-26 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0003_active_orders_remove_rentform_billing_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="active_orders",
            old_name="booking_id",
            new_name="user_id",
        ),
    ]
