# Generated by Django 4.1.1 on 2023-03-16 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0003_rename_user_name_rentform_user_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentform",
            name="date_now",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 3, 16, 18, 28, 3, 210904, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rentform",
            name="time",
            field=models.TimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 3, 16, 18, 28, 9, 788760, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
