# Generated by Django 4.1.1 on 2023-03-16 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0004_rentform_date_now_rentform_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rentform",
            old_name="hours",
            new_name="hourss",
        ),
        migrations.RenameField(
            model_name="rentform",
            old_name="new_price",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="rentform",
            name="date_now",
        ),
        migrations.RemoveField(
            model_name="rentform",
            name="time",
        ),
    ]
