# Generated by Django 4.1.1 on 2023-03-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0005_rename_hours_rentform_hourss_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentform",
            name="car_id",
            field=models.CharField(editable=False, max_length=60),
        ),
        migrations.AlterField(
            model_name="rentform",
            name="user_id",
            field=models.CharField(editable=False, max_length=60),
        ),
    ]
