# Generated by Django 4.1.1 on 2023-03-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0006_alter_rentform_car_id_alter_rentform_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentform",
            name="car_id",
            field=models.CharField(max_length=60),
        ),
    ]
