# Generated by Django 4.1.1 on 2023-03-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0008_alter_rentform_days_alter_rentform_hourss"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentform",
            name="Days",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="rentform",
            name="hourss",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
