# Generated by Django 4.1.1 on 2023-03-18 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0009_alter_rentform_days_alter_rentform_hourss"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentform",
            name="Days",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rentform",
            name="hourss",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 3, 18, 7, 23, 45, 345354, tzinfo=datetime.timezone.utc
                ),
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
