# Generated by Django 4.1.1 on 2023-03-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0010_alter_rentform_days_alter_rentform_hourss"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentform",
            name="total",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
