# Generated by Django 4.1.1 on 2023-03-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userbase",
            name="is_driver",
        ),
    ]
