# Generated by Django 4.1.1 on 2023-03-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbase",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="userbase",
            name="is_driver",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
