# Generated by Django 4.1.1 on 2023-03-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_base", "0002_remove_userbase_is_driver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userbase",
            name="car_image",
        ),
        migrations.RemoveField(
            model_name="userbase",
            name="car_luggage_space",
        ),
        migrations.RemoveField(
            model_name="userbase",
            name="car_name",
        ),
        migrations.RemoveField(
            model_name="userbase",
            name="car_seats",
        ),
    ]
